### ISSUE TITLE
Computer Version

### ISSUE THREAD

**Issue by Danila-Gosden** [huntmix/pentutor#1]
You should make version for linux/windows

**Comment by huntmix** [comment]
If you talk about access from linux/win to Pentutor, non logic.
If you talk about make tutorials to win and linux, i don't have enough users and resources, you can do your own category via tutorial in app.
In future maybe i will do, but not now... 
Because it free open source app, without donation activity, i have no motivation...

**Comment by Danila-Gosden** [comment]
If you need help with development, i can!

**Comment by huntmix** [comment]
> If you need help with development, i can!

App - open source, if you have idea how to optimise, add new features or other, you are welcome. You can add yours categories with https://huntmix.ru/welcome.html

**Comment by Danila-Gosden** [comment]
Okay, good)
